# Generated by Django 5.1.1 on 2024-12-13 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstorgae',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pharmacystorage',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='pharmacyorder',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='pharmacyorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pharmacystorage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lab',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LabInCity', to='app.city'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='MainOrder',
        ),
        migrations.DeleteModel(
            name='MainStorgae',
        ),
        migrations.DeleteModel(
            name='MedicalCategory',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.DeleteModel(
            name='PharmacyOrder',
        ),
        migrations.DeleteModel(
            name='PharmacyStorage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
