# Generated by Django 5.1.1 on 2024-12-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_alter_lab_name_pharmacy_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='city',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
