# Generated by Django 5.1.1 on 2024-12-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainStorageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('main_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Morder', to='app.mainstorageofproducts')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProdMainOrder', to='app.product')),
            ],
            options={
                'unique_together': {('main_storage', 'products', 'order_date')},
            },
        ),
    ]
