# Generated by Django 5.1.1 on 2024-12-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_composition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='city',
            new_name='location',
        ),
    ]
