# Generated by Django 5.1.1 on 2024-12-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_city_pharmacy_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categ',
        ),
    ]
